### ISSUE TITLE
Go Button Missing

### ISSUE THREAD

**Issue by tompearson** [cjslack/grok-debugger#7]
I'm not able to use the tool because it never fires off my pattern to the output. 
Missing is the autocomplete and Go button.
See screenshot.

![Grok-issue-1](https://user-images.githubusercontent.com/1223955/233857910-ece66c9f-038c-4022-ba01-84e1fa4a27e7.jpg)

**Comment by cjslack** [comment]
Hi, you have the inputs switched. The top input is for your pattern. The bottom one is for your logs. 

There is no go button, it will process automatically as you type
